export const galleryImages = [
  { src: "/images/hero-interior.jpg", alt: "Luxury living room interior design Bihar", width: 1376, height: 686 },
  { src: "/images/gypsum-ceiling.jpg", alt: "Gypsum false ceiling design Patna", width: 1080, height: 1144 },
  { src: "/images/pvc-ceiling.jpg", alt: "PVC ceiling installation Lauriya", width: 1084, height: 1434 },
  { src: "/images/wpc-louvers.jpg", alt: "WPC louvers wall panel Bihar", width: 1228, height: 1600 },
  { src: "/images/tv-unit.jpg", alt: "Modern TV unit design Patna", width: 1024, height: 1024 },
  { src: "/images/gallery-1.jpg", alt: "Designer bedroom interior Bettiah", width: 1024, height: 1024 },
  { src: "/images/gallery-2.jpg", alt: "Modular kitchen interior Bihar", width: 1024, height: 1024 },
  { src: "/images/gallery-3.jpg", alt: "Professional office interior Patna", width: 1024, height: 1024 },
  { src: "/images/gallery-4.jpg", alt: "Luxury drawing room false ceiling", width: 1024, height: 1024 },
  { src: "/images/fluted-panels.jpg", alt: "Fluted wall panels TV unit", width: 1800, height: 1351 },
  { src: "/images/uv-marble.jpg", alt: "UV marble sheet wall design", width: 1024, height: 1024 },
  { src: "/images/artificial-grass.jpg", alt: "Artificial grass balcony decoration", width: 1024, height: 1024 },
  { src: "/images/gallery-5.jpg", alt: "Gypsum ceiling design for bedroom Lauriya", width: 1084, height: 1245 },
  { src: "/images/gallery-6.jpg", alt: "PVC ceiling panels modern home Bihar", width: 1200, height: 1600 },
  { src: "/images/gallery-7.jpg", alt: "WPC louvers living room wall design", width: 1129, height: 1286 },
  { src: "/images/gallery-8.jpg", alt: "Luxury TV unit with LED panel Patna", width: 1280, height: 960 },
  { src: "/images/gallery-9.jpg", alt: "Modular kitchen interior design Bihar", width: 686, height: 386 },
  { src: "/images/gallery-10.jpg", alt: "Office false ceiling gypsum work", width: 1355, height: 1800 },
  { src: "/images/gallery-11.jpg", alt: "Fluted panels bedroom headboard design", width: 1084, height: 1257 },
  { src: "/images/gallery-12.jpg", alt: "UV marble sheet TV wall Lauriya", width: 1084, height: 1202 },
  { src: "/images/gallery-13.jpg", alt: "Artificial grass balcony decoration", width: 1202, height: 1500 },
  { src: "/images/gallery-14.jpg", alt: "Designer drawing room ceiling", width: 574, height: 1280 },
  { src: "/images/gallery-15.jpg", alt: "PVC wall paneling for shop", width: 1084, height: 801 },
  { src: "/images/gallery-16.jpg", alt: "WPC ceiling outdoor area", width: 980, height: 1280 },
  { src: "/images/gallery-17.jpg", alt: "Gypsum partition wall design", width: 1200, height: 1600 },
  { src: "/images/gallery-18.jpg", alt: "Modern bedroom interior Bihar", width: 1200, height: 1600 },
  { src: "/images/gallery-19.jpg", alt: "Luxury kitchen with island", width: 1200, height: 1600 },
  { src: "/images/gallery-20.jpg", alt: "Office cabin interior design", width: 576, height: 1280 },
  { src: "/images/gallery-21.jpg", alt: "Living room false ceiling with cove light", width: 1600, height: 1204 },
  { src: "/images/gallery-22.jpg", alt: "PVC louvers exterior design", width: 1200, height: 1600 },
  { src: "/images/gallery-23.jpg", alt: "TV cabinet with fluted panels", width: 1200, height: 1600 },
  { src: "/images/gallery-24.jpg", alt: "Restaurant interior ceiling work", width: 1600, height: 1200 },
  { src: "/images/gallery-25.jpg", alt: "Bedroom PVC ceiling design", width: 720, height: 720 },
  { src: "/images/gallery-26.jpg", alt: "Hall gypsum design Lauriya Nandangarh", width: 1200, height: 1600 },
  { src: "/images/gallery-27.jpg", alt: "WPC deck flooring balcony", width: 1280, height: 577 },
  { src: "/images/gallery-28.jpg", alt: "Modular wardrobe design", width: 1080, height: 1350 },
  { src: "/images/gallery-29.jpg", alt: "UV board kitchen shutters", width: 1280, height: 960 },
  { src: "/images/gallery-30.jpg", alt: "False ceiling for shop Bihar", width: 1280, height: 960 },
  { src: "/images/gallery-31.jpg", alt: "3D wall panel living room", width: 1280, height: 960 },
  { src: "/images/gallery-32.jpg", alt: "Gypsum ceiling with fan design", width: 1080, height: 1080 },
  { src: "/images/gallery-33.jpg", alt: "PVC ceiling bathroom waterproof", width: 468, height: 1040 },
  { src: "/images/gallery-34.jpg", alt: "Office reception interior", width: 1200, height: 1600 },
  { src: "/images/gallery-35.jpg", alt: "Bedroom wall WPC louvers", width: 1204, height: 1600 },
  { src: "/images/gallery-36.jpg", alt: "TV unit with marble finish", width: 960, height: 1280 },
  { src: "/images/gallery-37.jpg", alt: "Kitchen ceiling PVC panels", width: 1600, height: 1204 },
  { src: "/images/gallery-38.jpg", alt: "Living room interior Lauriya", width: 736, height: 552 },
  { src: "/images/gallery-39.jpg", alt: "Gypsum arch design", width: 1200, height: 1600 },
  { src: "/images/gallery-40.jpg", alt: "Fluted panel pooja room", width: 736, height: 952 },
  { src: "/images/gallery-41.jpg", alt: "Artificial grass wall decor", width: 736, height: 736 },
  { src: "/images/gallery-42.jpg", alt: "Complete home interior Bihar", width: 720, height: 1280 },
]

export function buildGalleryJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "ImageGallery",
    name: "Interior Design & False Ceiling Projects - Bihar Patna",
    description:
      "Portfolio of false ceiling, PVC panels, WPC louvers, TV unit, modular kitchen and bedroom interior design projects in Bihar and Patna.",
    image: galleryImages.map((img) => `https://www.jkinterior.online${img.src}`),
  }
}
